version: '2'
services:
    controller:
        container_name: flask_tester
        hostname: flask_tester
        image: flask_tester:0.1
        volumes:
            - /mnt/code/flask-tester-backend:/src
        ports:
            - "80:80"
