version: '2'
services:
    flask_tester_app:
        container_name: flask_tester
        hostname: flask_tester
        image: flask_tester:0.2
        volumes:
            - /mnt/code/flask-tester-backend:/src
        ports:
            - "80:80"
        depends_on:
            - redis
    redis:
        container_name: flask_tester_redis
        hostname: flask_tester_redis
        image: redis:3.2.5
        command: redis-server --appendonly yes
        volumes:
            - /mnt/code/flask-tester-docker/data/redis:/data
        ports:
            - "6379:6379"
